### ISSUE TITLE
RuntimeError at /

### ISSUE THREAD

**Issue by skolos** [michaek/middleman-navigation#4]
I followed instructions from README. 
When trying to run = render_navigation I've got the following error:

RuntimeError at /
no primary navigation defined, either use a navigation config file or pass items directly to render_navigation

I am not sure if it maters - I am using slim templates.

**Comment by michaek** [comment]
I've seen this happen if no pages are configured to appear in the menu.
Regardless, we should recover better from simple_navigation's error.

**Comment by dallasbpeters** [comment]
I'm seeing this as well. 

```
---
navigation:
  weight: 80
  title:  Title
  hidden: false
---
```

this is at the top of my index.html.haml file. Can we use haml?

**Comment by dallasbpeters** [comment]
if it helps

```
RuntimeError at /
no primary navigation defined, either use a navigation config file or pass items directly to render_navigation
/Users/admin/.rvm/gems/ruby-1.9.3-p392/gems/simple-navigation-3.11.0/lib/simple_navigation/rendering/helpers.rb: in load_config, line 114
```

**Comment by bryanbraun** [comment]
Any advice on how to define primary navigation in this case? I found [this documentation](https://github.com/andi/simple-navigation/wiki/Configuration) under the Simple Navigation project, but I'm not sure if the same instructions would apply here.

**Comment by michaek** [comment]
Unfortunately, I don't remember what causes this error exactly. It's been a while since I used middleman, but I remember that having at least one page with a 'title' in the frontmatter was good enough.

**Comment by michaek** [comment]
I'm not able to reproduce this now, though I've added a test to try to trigger it. If it's still live, we'll reopen it.

**Comment by maxlinc** [comment]
I see this when I run `middleman build`, but not `middleman server`. I have an http_prefix and a custom build directory (because I'm building to deploy to github pages for a project, which deploys to a subpath).

I tracked it down to [tree.rb#L6](https://github.com/michaek/middleman-navigation/blob/4feda88a83dd7996f286b3072b18c53e19c8a8d6/lib/middleman-navigation/tree.rb#L6). It's currently:

``` ruby
@root = sitemap.find_resource_by_destination_path @app.http_prefix+@app.index_file
```

If I drop the `@app.http_prefix`, it works for me for both server (which doesn't use a prefix) and build (which does):

``` ruby
@root = sitemap.find_resource_by_destination_path @app.index_file
```

I don't know the middleman api that way, but it might be even more correct if you look up by path instead of destination path. This also works:

``` ruby
@root = sitemap.find_resource_by_path @app.index_file
```

I'll send a PR...
